title: FUComplete
description: FUComplete is a modification of MHP2G, aiming to be feature complete and add new features to the game.
theme: just-the-docs

logo: "/assets/images/patch_logo.png"
color_scheme: fuc

collections:
  files_doc:
    output: true
  datamine_doc:
    output: true
  tutorials:
    output: true
  links:
    output: true

just_the_docs:
  collections:
    files_doc:
      name: Documentation
    datamine_doc:
      name: Data Mines
    tutorials:
      name: Tutorials
    links:
      name: Links

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

url: https://fucomplete.github.io

nav_external_links:
  - title: FUComplete Config Editor
    url: ./assets/config_editor.html
    hide_icon: false
    opens_in_new_tab: true

mermaid:
  version: "10.8.0"

# aux_links_new_tab: true
# aux_links:
#   "FUComplete Config Editor": 
#     - ../../assets/config_editor.html
