title: FUComplete
description: Documentation on Monster Hunter Freedom Unite, Portable 2nd G and FUComplete Patch.
theme: just-the-docs

logo: "/assets/images/patch_logo.png"
color_scheme: dark

callouts:
  note:
    title: Note
    color: blue

url: https://fucomplete.github.io

nav_external_links:
  - title: FUComplete Config Editor
    url: ./assets/config_editor.html
    hide_icon: false
    opens_in_new_tab: true

mermaid:
  version: "10.8.0"

aux_links:
#  Download Patch: https://github.com/FUComplete/Patch
